[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_20"]

[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-dev --no-interaction --prefer-dist"
]

[phases.build]
cmds = [
    "mkdir -p storage/framework/{sessions,views,cache,testing} storage/logs bootstrap/cache",
    "chmod -R 775 storage bootstrap/cache"
]

[start]
cmd = "bash railway-start.sh"

